/*
 * Copyright (c) 2019-2026 Philippe Riand
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.monflabs.galtajs.rt.builtins;

import java.util.Arrays;

import org.eclipse.jdt.annotation.NonNull;
import org.monflabs.galtajs.rt.RuntimeUtil;

public interface Callable {

	// Thread-local single-slot pool of Object[] bridge arrays, indexed by arity.
	// Used by callers that must build a transient parameter array to reach a
	// wider-Object[] entry point (BuiltinFunctionTranspiler.callVoidN defaults +
	// Callable.call(_this, p1..pN) defaults). The arrays MUST NOT outlive the
	// callee's return - only pool via acquireBridge()/releaseBridge() around a
	// synchronous callee dispatch, never hand a pooled array to code that could
	// retain it. Arity 0 uses RuntimeUtil.EMPTY_PARAMS directly and is not pooled.
	final class ArrayPool {
		private ArrayPool() {}
		private static final ThreadLocal<Object[][]> SLOTS = ThreadLocal.withInitial(() -> new Object[MAX_DIRECT_ARITY+1][]);

		public static Object[] acquire(int arity) {
			Object[][] slots = SLOTS.get();
			Object[] a = slots[arity];
			if(a!=null) {
				slots[arity] = null;
				return a;
			}
			return new Object[arity];
		}

		public static void release(Object[] a) {
			int arity = a.length;
			if(arity==0 || arity>MAX_DIRECT_ARITY) return;
			Object[][] slots = SLOTS.get();
			// A recursive/reentrant acquire that we couldn't satisfy from the
			// slot has already allocated a fresh array - drop this one on the
			// floor rather than growing the slot into a stack.
			if(slots[arity]!=null) return;
			Arrays.fill(a, null);
			slots[arity] = a;
		}
	}


	// Highest positional-argument count that avoids allocating an Object[] at
	// the call site. Callers with arity <= this and no spread emit direct
	// `call(_this,p1,...,pN)` (see ASTBaseCall.transpileParams); BuiltinFunctionTranspiler
	// overrides those overloads to route to arity-specific callVoid variants
	// generated by ASTFunction. Larger arities and spread calls fall back to
	// the Object[] path. Raising this ceiling costs one Callable default method +
	// one BuiltinFunctionTranspiler override per new arity — proportional, not free.
	public static final int MAX_DIRECT_ARITY = 10;

	public Object call(Object _this, @NonNull Object[] parameters);

	public default boolean isForceStrict() {
		return false;
	}

	// Spec IsCallable(argument): whether this object genuinely has a [[Call]]
	// internal method - distinct from merely implementing this Java
	// interface, which BuiltinProxy does unconditionally for dispatch
	// convenience regardless of whether its wrapped target is genuinely
	// callable (typeof on a Proxy wrapping a non-callable target must report
	// "object", not "function").
	public default boolean isCallable() {
		return true;
	}


	// Convenience methods
	// Note that an implementation might override some of these for optimization purposes
	public default Object call() {
		return call(null, RuntimeUtil.EMPTY_PARAMS);
	}
	public default Object call(Object _this) {
		return call(_this, RuntimeUtil.EMPTY_PARAMS);
	}
	public default Object call(Object _this, Object p1) {
		return call(_this, new Object[] {p1});
	}
	public default Object call(Object _this, Object p1, Object p2) {
		return call(_this, new Object[] {p1,p2});
	}
	public default Object call(Object _this, Object p1, Object p2, Object p3) {
		return call(_this, new Object[] {p1,p2,p3});
	}
	public default Object call(Object _this, Object p1, Object p2, Object p3, Object p4) {
		return call(_this, new Object[] {p1,p2,p3,p4});
	}
	public default Object call(Object _this, Object p1, Object p2, Object p3, Object p4, Object p5) {
		return call(_this, new Object[] {p1,p2,p3,p4,p5});
	}
	public default Object call(Object _this, Object p1, Object p2, Object p3, Object p4, Object p5, Object p6) {
		return call(_this, new Object[] {p1,p2,p3,p4,p5,p6});
	}
	public default Object call(Object _this, Object p1, Object p2, Object p3, Object p4, Object p5, Object p6, Object p7) {
		return call(_this, new Object[] {p1,p2,p3,p4,p5,p6,p7});
	}
	public default Object call(Object _this, Object p1, Object p2, Object p3, Object p4, Object p5, Object p6, Object p7, Object p8) {
		return call(_this, new Object[] {p1,p2,p3,p4,p5,p6,p7,p8});
	}
	public default Object call(Object _this, Object p1, Object p2, Object p3, Object p4, Object p5, Object p6, Object p7, Object p8, Object p9) {
		return call(_this, new Object[] {p1,p2,p3,p4,p5,p6,p7,p8,p9});
	}
	public default Object call(Object _this, Object p1, Object p2, Object p3, Object p4, Object p5, Object p6, Object p7, Object p8, Object p9, Object p10) {
		return call(_this, new Object[] {p1,p2,p3,p4,p5,p6,p7,p8,p9,p10});
	}
}
