/*
 * Copyright (c) 2019-2026 Philippe Riand
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.monflabs.galtajs.node.clazz;

import java.util.Collections;
import java.util.List;

import org.monflabs.galtajs.node.ASTNode;
import org.monflabs.galtajs.node.control.ASTFunctionMethod;
import org.monflabs.galtajs.parser.Token;
import org.monflabs.galtajs.rt.RuntimeUtil;
import org.monflabs.galtajs.rt.builtins.Constructor;
import org.monflabs.galtajs.rt.builtins.privatename.PrivateName;
import org.monflabs.galtajs.rt.builtins.standard.function.BuiltinClassConstructor;
import org.monflabs.galtajs.rt.builtins.standard.function.BuiltinFunction;
import org.monflabs.galtajs.rt.interpreter.JSInterpretedRuntimeContext;
import org.monflabs.galtajs.transpiler.TranspilerJavaBuilder;
import org.monflabs.galtajs.transpiler.context.JSTranspilerGeneratorContext;
import org.monflabs.galtajs.util.JavaBuilder;
import org.monflabs.util.StringUtil;


/**
 * Class methods.
 */
public class ASTClassMethod extends ASTClassMember {
	
	private ASTFunctionMethod functionDecl;
	private boolean constructor;
	private boolean autoGenerated;
	
	public ASTClassMethod(Token t, Object name, ASTFunctionMethod functionDecl, boolean isStatic, boolean isPrivate, boolean autoGenerated) {
		this(t,name,functionDecl,isStatic,isPrivate,autoGenerated,Collections.emptyList());
	}
	public ASTClassMethod(Token t, Object name, ASTFunctionMethod functionDecl, boolean isStatic, boolean isPrivate, boolean autoGenerated, List<ASTNode> decorators) {
		super(t,name,isStatic, isPrivate,decorators);
		this.functionDecl = assignParent(functionDecl);
		// A method literally named "constructor" is only THE special class
		// constructor when it's a plain, non-static instance method - per
		// spec, "static MethodDefinition"'s own early-error rules never
		// mention "constructor" at all (only HasDirectSuper and PropName==
		// "prototype"), so `static constructor(){}`/`static *constructor(){}`
		// etc. are ordinary static methods that merely happen to share the
		// name, not a syntax error (confirmed via test262's grammar-static-
		// ctor-*-meth-valid.js matrix). Only a NON-static "constructor" is
		// ever special, and only THEN do the static/private restrictions
		// below even apply.
		this.constructor = !isStatic && StringUtil.equals(getName(),Constructor.CONSTRUCTOR);
		if(constructor) {
			if(isPrivate) {
				throw RuntimeUtil.syntaxError("A constructor cannot be private");
			}
		}
		this.autoGenerated = autoGenerated;
	}

	public ASTFunctionMethod getFunctionDecl() {
		return functionDecl;
	}

	public boolean isConstructor() {
		return constructor;
	}
	
	@Override
	public boolean isAutoGenerated() {
		return autoGenerated;
	}
	
	@Override
	public int getChildCount() {
		return super.getChildCount()+1;
	}
	@Override
	public ASTNode getChild(int index) {
		switch(index) {
			case 0 ->	{ return functionDecl; }
			default ->	{ return super.getChild(index-1); }
		}
	}
	@Override
	protected void _setChild(int index, ASTNode node) {
		switch(index) {
			case 0 ->	{ this.functionDecl = (ASTFunctionMethod)node; }
			default ->  { super._setChild(index-1,node); }
		}
	}

	@Override
	public void initClass(JSInterpretedRuntimeContext context, BuiltinClassConstructor clazz) {
		Object name = evaluateName(context, clazz);
		BuiltinFunction function = applyOwnDecorators(context, name, createFunction(context, functionDecl));
		if(!isStatic()) {
			if(constructor) {
				clazz.addClassConstructor((String)name, function);
			} else {
				clazz.addClassMethod(name, function);
				if(isPrivate()) {
					setPrivateInstanceFunction(clazz, function);
				}
			}
		} else {
			clazz.addClassStaticMethod(name, function);
		}
	}
	// A decorator returning a non-BuiltinFunction Callable (e.g. some other
	// Callable implementor) is silently NOT applied as a replacement, rather
	// than risking a ClassCastException - addClass{,Static}Method/Constructor
	// require BuiltinFunction specifically.
	private BuiltinFunction applyOwnDecorators(JSInterpretedRuntimeContext context, Object name, BuiltinFunction function) {
		Object result = applyDecorators(context, getDecorators(), function, "method", name, isStatic(), isPrivate());
		return result instanceof BuiltinFunction bf ? bf : function;
	}

	@Override
	public void initInstance(JSInterpretedRuntimeContext context, BuiltinClassConstructor clazz, Object instance) {
		// Private (non-static, non-constructor) methods: PrivateMethodOrAccessorAdd
		// copies a reference to the SAME shared function (created once, above,
		// during initClass) onto EACH new instance's own [[PrivateElements]] -
		// private access never walks the prototype chain, so it must exist on
		// the instance itself, unlike a public method (found once, on the
		// shared prototype).
		if(!isStatic() && !constructor && isPrivate()) {
			PrivateName name = (PrivateName)evaluateName(context, clazz);
			clazz.addInstancePrivateMethod(instance, name, getPrivateInstanceFunction(clazz));
		}
	}
	
	@Override
	public void transpileInitClassStatement(JSTranspilerGeneratorContext _jsContext, TranspilerJavaBuilder b, String clazzVar, int memberIndex) {
		if(!isStatic()) {
			if(constructor) {
				b.println("{0}.addClassConstructor({1},", clazzVar, transpileNameExpression(_jsContext, clazzVar));
				b.incIndent();
				b.println("{0}", functionDecl.transpileJavaExpression(_jsContext));
				b.decIndent();
				b.println(");");
			} else if(isPrivate()) {
				// The shared function value is created once here and reused by
				// every later initInstance call for THIS evaluation - see
				// ASTClassDecl's priv_N field and needsPrivateInstanceFunctionField.
				b.println("priv_{0} = {1};", memberIndex, functionDecl.transpileJavaExpression(_jsContext));
				b.println("{0}.addClassMethod({1}, priv_{2});", clazzVar, transpileNameExpression(_jsContext, clazzVar), memberIndex);
			} else {
				b.println("{0}.addClassMethod({1},", clazzVar, transpileNameExpression(_jsContext, clazzVar));
				b.incIndent();
				b.println("{0}", functionDecl.transpileJavaExpression(_jsContext));
				b.decIndent();
				b.println(");");
			}
		} else {
			b.println("{0}.addClassStaticMethod({1},", clazzVar, transpileNameExpression(_jsContext, clazzVar));
			b.incIndent();
			b.println("{0}", functionDecl.transpileJavaExpression(_jsContext));
			b.decIndent();
			b.println(");");
		}
    }

	@Override
	public void transpileInitInstanceStatement(JSTranspilerGeneratorContext _jsContext, TranspilerJavaBuilder b, String clazzVar, String instanceVar, int memberIndex) {
		// See ASTClassMethod.initInstance (interpreted mode): PrivateMethodOrAccessorAdd
		// copies a reference to the SAME shared function onto EACH new
		// instance's own [[PrivateElements]] - private access never walks the
		// prototype chain.
		if(!isStatic() && !constructor && isPrivate()) {
			b.println("{0}.addInstancePrivateMethod({1}, {2}, priv_{3});", clazzVar, instanceVar, transpileNameExpression(_jsContext, clazzVar), memberIndex);
		}
    }
	
	@Override
	public void decompile(JavaBuilder b) {
		if(isStatic()) {
			b.append("static ");
		}
		ASTNode namedNode = getNameNode();
		if(namedNode!= null) {
			b.append('[');
			b.append(namedNode.decompileExpression());
			b.append(']');
		} else {
			if(isPrivate()) {
				b.append('#');
			}
			b.append(getName());
		}
		b.append(" ");
		b.append(functionDecl.decompileFunction());
		b.append("\n");
	}
}
