<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	
	<parent>
		<groupId>org.monflabs.galta</groupId>
		<artifactId>parent-ui</artifactId>
		<version>${revision}</version>
	</parent>
	<artifactId>parent-ui-commons</artifactId>
	<packaging>pom</packaging>
	<name>Galta UI Commons Parent</name>
	<description>Parent of the toolkit-independent UI modules.</description>

	<modules>
		<module>ui-commons</module>
	</modules>

</project>