<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	
	<parent>
		<groupId>org.monflabs.galta.tools</groupId>
		<artifactId>tools</artifactId>
		<version>${revision}</version>
	</parent>
	<artifactId>parent-tools-maven</artifactId>
	<packaging>pom</packaging>
	<name>Galta Tools - Maven Plugins Parent</name>
	<description>Parent of the Galta Maven plugins.</description>

	<modules>
		<module>filesystem-resources-manifest</module>
	</modules>
	
	<properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>

		<!-- Java Configuration -->
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
	</properties>

    <dependencyManagement>
        <dependencies>
			<!-- https://mvnrepository.com/artifact/org.apache.maven/maven-plugin-api -->
			<dependency>
				<groupId>org.apache.maven</groupId>
				<artifactId>maven-plugin-api</artifactId>
				<version>3.8.6</version>
			</dependency>
			<!-- https://mvnrepository.com/artifact/org.apache.maven/maven-core -->
			<dependency>
				<groupId>org.apache.maven</groupId>
				<artifactId>maven-core</artifactId>
				<version>3.8.6</version>
			</dependency>
        </dependencies>
    </dependencyManagement>
	
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<source>${maven.compiler.source}</source>
					<target>${maven.compiler.target}</target>
				</configuration>
			</plugin>
		</plugins>
			
		<!-- see: https://stackoverflow.com/questions/60861485/maven-plugin-plugin3-2descriptor-failed-index-22273-out-of-bounds-for-length -->
		<pluginManagement>
	        <plugins>
				<!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-compiler-plugin -->
	            <plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-compiler-plugin</artifactId>
				    <version>3.11.0</version>
                </plugin>
				<!-- https://mvnrepository.com/artifact/org.apache.maven.plugins/maven-plugin-plugin -->
	            <plugin>
				    <groupId>org.apache.maven.plugins</groupId>
				    <artifactId>maven-plugin-plugin</artifactId>
				    <version>3.10.2</version>
                </plugin>
				<!-- https://mvnrepository.com/artifact/org.codehaus.mojo/build-helper-maven-plugin -->
				<plugin>
				    <groupId>org.codehaus.mojo</groupId>
				    <artifactId>build-helper-maven-plugin</artifactId>
				    <version>3.6.0</version>
				</plugin>
	        </plugins>
		</pluginManagement>
	</build>

</project>