<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	
	<parent>
		<groupId>org.monflabs.galta.tools</groupId>
		<artifactId>tools</artifactId>
		<version>${revision}</version>
	</parent>

	<artifactId>parent-tools-bom</artifactId>
	<packaging>pom</packaging>
	<name>Galta Tools - BOM Parent</name>
	<description>Parent of the Galta dependency BOM.</description>

	<modules>
		<module>monflabs-bom</module>
	</modules>

</project>