<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	
	<parent>
		<groupId>org.monflabs.galta</groupId>
		<artifactId>parent-js</artifactId>
		<version>${revision}</version>
	</parent>
	<artifactId>parent-js-precompiled</artifactId>
	<packaging>pom</packaging>
	<name>GaltaJS Precompiled Libraries Parent</name>
	<description>Parent of JavaScript libraries transpiled to Java with GaltaJS at build time.</description>


	<modules>
		<module>js-precompiled-beautify-css</module>
		<module>js-precompiled-beautify-html</module>
		<module>js-precompiled-beautify-js</module>
		<module>js-precompiled-typescript</module>
	</modules>

</project>