assertTrue( Object.is(null,null) )
assertFalse( Object.is(null,1) )
assertFalse( Object.is(1,null) )
assertFalse( Object.is([],null) )
assertFalse( Object.is({},null) )

assertTrue( Object.is(true,true) )
assertTrue( Object.is(false,false) )
assertFalse( Object.is(true,false) )
assertFalse( Object.is(true,1) )

assertTrue( Object.is("","") )
assertTrue( Object.is("ABC","ABC") )
assertFalse( Object.is("",null) )
assertFalse( Object.is("ABC","abc") )
assertFalse( Object.is("",[]) )
assertFalse( Object.is("",[""]) )

assertTrue( Object.is(0,0) )
assertTrue( Object.is(-0.0,-0.0) )
assertTrue( Object.is(+0.0,+0.0) )
assertFalse( Object.is(+0.0,-0.0) )
assertTrue( Object.is(1,1) )
assertTrue( Object.is(1,1.0) )
assertTrue( Object.is(1,1L) )
assertTrue( Object.is(1,1.0f) )
assertTrue( Object.is(1,1.0d) )
assertTrue( Object.is(1,1.0m) )
assertTrue( Object.is(NaN,NaN) )
assertFalse( Object.is(1,true) )
assertFalse( Object.is(0,false) )
assertFalse( Object.is(1,2) )
assertFalse( Object.is(1,[1]) )
assertFalse( Object.is(1,{}) )


const o={}, a=[];
assertTrue( Object.is(o,o) )
assertTrue( Object.is(a,a) )
assertFalse( Object.is({},o) )
assertFalse( Object.is({},{}) )
assertFalse( Object.is([],a) )
assertFalse( Object.is([],[]) )
