assertTrue(1>=0)
assertTrue(1>=1)
assertTrue(1>=0L)
assertTrue(1>=1L)
assertTrue(1>=0n)
assertTrue(1>=1n)
assertTrue(1>=1.0f)
assertTrue(1>=0.0)
assertTrue(1>=0m)
assertTrue(1>=1.0m)
assertTrue(true>=false)
assertTrue(true>=true)
assertTrue('a'>='a')
assertTrue('b'>='a')

assertFalse(0>=1)
assertFalse(0>=1L)
assertFalse(0>=1n)
assertFalse(0>=1.0f)
assertFalse(0>=1.0)
assertFalse(0>=1m)
assertFalse(false>=true)
assertFalse('a'>='b')

assertFalse(1>=+Infinity)
assertTrue(1>=-Infinity)
assertTrue(+Infinity>=+Infinity)
assertTrue(+Infinity>=-Infinity)
assertFalse(-Infinity>=+Infinity)
assertTrue(-Infinity>=-Infinity)

assertTrue(null>=-1)
assertTrue(null>=0)
assertFalse(null>=1)
assertFalse(-1>=null)
assertTrue(0>=null)
assertTrue(1>=null)

assertFalse(1>=NaN)
assertFalse(NaN>=1)
assertFalse(NaN>=NaN)

assertFalse(1>=undefined)
assertFalse(undefined>=1)
assertFalse(undefined>=NaN)
assertFalse(NaN>=undefined)
assertFalse(undefined>=undefined)

assertTrue(22*>=22)
assertFalse('abc'*>='xyz')
