assertFalse(1<0)
assertFalse(1<1)
assertFalse(1<0L)
assertFalse(1<1L)
assertFalse(1<0n)
assertFalse(1<1n)
assertFalse(1<1.0f)
assertFalse(1<1.0)
assertFalse(1<1.0m)
assertFalse(true<false)
assertFalse(true<true)
assertFalse('a'<'a')
assertFalse('b'<'a')

assertTrue(0<1)
assertTrue(0<1L)
assertTrue(0<1n)
assertTrue(0<1.0f)
assertTrue(0<1.0)
assertTrue(0<1m)
assertTrue(false<true)
assertTrue('a'<'b')

assertTrue(1<+Infinity)
assertFalse(1<-Infinity)
assertFalse(+Infinity<+Infinity)
assertFalse(+Infinity<-Infinity)
assertTrue(-Infinity<+Infinity)
assertFalse(-Infinity<-Infinity)

assertFalse(null<-1)
assertFalse(null<0)
assertTrue(null<1)
assertTrue(-1<null)
assertFalse(0<null)
assertFalse(1<null)

assertFalse(1<NaN)
assertFalse(NaN<1)
assertFalse(NaN<NaN)

assertFalse(1<undefined)
assertFalse(undefined<1)
assertFalse(undefined<NaN)
assertFalse(NaN<undefined)
assertFalse(undefined<undefined)

assertFalse(22*<22)
assertTrue('abc'*<'xyz')
