assertFalse(1!=1)
assertFalse(1!=1L)
assertFalse(1!=1n)
assertFalse(1!=1.0f)
assertFalse(1!=1.0)
assertFalse(1!=1.0m)
assertFalse(true!=true)
assertFalse(false!=false)
assertFalse('a'!='a')

assertTrue(1!=0)
assertTrue(1!=0L)
assertTrue(1!=0n)
assertTrue(1!=0.0f)
assertTrue(1!=0.0)
assertTrue(1!=0.0m)
assertTrue(true!=false)
assertTrue(false!=true)
assertTrue('a'!='b')
assertTrue('b'!='a')

assertTrue(true==true)
assertFalse(1!='1')
assertFalse(1!=[1])
assertFalse(1!=['1'])
assertFalse('1'!=['1'])
assertFalse('1'!=[1])
assertFalse(1!=true)
assertTrue(2!=true)

assertTrue(null!=0)
assertTrue(null!=1)
assertTrue(0!=null)
assertTrue(1!=null)

assertTrue(null!=NaN)
assertTrue(NaN!=null)
assertTrue(NaN!=NaN)

assertFalse(22*!=22)
assertTrue('abc'*!='xyz')
