/*
 * Copyright (c) 2019-2026 Philippe Riand
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.monflabs.tools.maven;

import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.util.Arrays;

import org.apache.maven.plugin.AbstractMojo;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugins.annotations.LifecyclePhase;
import org.apache.maven.plugins.annotations.Mojo;
import org.apache.maven.plugins.annotations.Parameter;
import org.apache.maven.project.MavenProject;

/**
 * Generates the manifest listing the files of a resource directory, which the
 * classpath-based ResourceFileSystem reads to list directories. The manifest
 * is written into that directory, and only rewritten when its content changes.
 */
@Mojo(
		name = "generate-sources",
		defaultPhase = LifecyclePhase.GENERATE_SOURCES,
		threadSafe = true
)
public class VfsResourceManifestMojo extends AbstractMojo {

	@Parameter(defaultValue = "${project}", readonly = true, required = true)
	MavenProject project;

	/**
	 * The resource directory to list, relative to the project's base directory.
	 */
	@Parameter(required = true)
	String sourceDirectory;

	/**
	 * The name of the manifest file, written in the source directory.
	 */
	@Parameter(defaultValue = "resources.manifest")
	String manifestName;

	/**
	 * Whether the file lengths are recorded (otherwise -1).
	 */
	@Parameter(defaultValue = "false")
	boolean length;

	/**
	 * The date recorded for the files: a fixed date (default
	 * 2020-01-01T00:00:00Z, keeping the manifest stable), "now", "file" (each
	 * file's last modification) or "none".
	 */
	@Parameter
	String date;

	@Override
	public void execute() throws MojoExecutionException {
		File baseDir = project.getFile().getParentFile(); // Parent of pom.xml
		File vfsDir = new File(baseDir,sourceDirectory);
		if(!vfsDir.isDirectory()) {
			throw new MojoExecutionException("Invalid VFS directory " + vfsDir + ": not a directory");
		}
		try {

			String fixedDateString = "2020-01-01T00:00:00Z";
			if(date!=null && date.length()>0) {
				if(date.equals("now")) {
					fixedDateString = Instant.now().toString();
				} else if(date.equals("file")) {
					fixedDateString = "file";
				} else if(date.equals("none")) {
					fixedDateString = null;
				} else {
					fixedDateString = date; 
				}
			}
			
			StringBuilder sb = new StringBuilder(2048);
			sb.append("# Generated by Maven plugin\n");
			addFiles( sb, vfsDir.toPath(), vfsDir, fixedDateString);
			String newContent = normalizeLineBreaks(sb.toString());
			
			Path manifest = vfsDir.toPath().resolve(manifestName);
			if(Files.isRegularFile(manifest)) {
				String oldContent = normalizeLineBreaks(Files.readString(manifest, StandardCharsets.UTF_8));
				if(oldContent.equals(newContent)) {
					// Ok, do not override it...
					return;
				}
			}
			Files.writeString(manifest, newContent, StandardCharsets.UTF_8);
		} catch (IOException | RuntimeException e) {
			throw new MojoExecutionException("VFS manifest generation failed for " + vfsDir + ": " + e.getMessage(), e);
		}
	}
	
	public static String normalizeLineBreaks(String s) {
		if(s!=null && s.indexOf('\r')>=0) {
			// Normalize the lines breaks to make it compatible between the different platforms (Mac, Windows, ....)
			s = s.replace("\n\r", "\n");
			s = s.replace("\r\n", "\n");
			s = s.replace("\r", "\n");
		}
		return s;
	}
	
	private void addFiles(StringBuilder sb, Path basePath, File dir, String fixedDateString) throws IOException {
		File[] files = dir.listFiles();
		if(files==null) {
			throw new IOException("Cannot list the directory " + dir);
		}
		Arrays.sort(files, (f1,f2) -> {
			boolean l1 = f1.isDirectory();
			boolean l2 = f2.isDirectory();
			if(l1!=l2) {
				return l1 ? 1 : -1;
			}
			return f1.getName().compareToIgnoreCase(f2.getName());
		});
		for(int i=0; i<files.length; i++) {
			File f = files[i];
			if(f.isFile() && accept(f)) {
				String path  = basePath.relativize(f.toPath()).toString();
				if(File.separatorChar!='/') {
					path = path.replace(File.separatorChar, '/');
				}
				if(!manifestName.equals(path)) {
					long lastModified = f.lastModified();
					sb.append(path);
					sb.append('\t');
					if(length) {
						sb.append(f.length());
					} else {
						sb.append(-1);
					}
					if(fixedDateString!=null) {
						sb.append('\t');
						if(fixedDateString.equals("file")) {
							String dateAsString = Instant.ofEpochMilli(lastModified).toString();
							sb.append(dateAsString);
						} else {
							sb.append(fixedDateString);
						}
					}
					sb.append('\n');
				}
			} else if(f.isDirectory()) {
				addFiles(sb,basePath,f,fixedDateString);
			}
		}
	}
	
	private boolean accept(File f) {
		String name = f.getName();
		if(name.equals(".DS_Store")) {
			return false;
		}
		if(name.equals(".gitignore")) {
			return false;
		}
		if(name.equals(".gitattributes")) {
			return false;
		}
		return true;
	}
}
