/*
 * Copyright (c) 2019-2026 Philippe Riand
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.monflabs.tools.maven;

import java.io.File;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.Writer;
import java.nio.charset.StandardCharsets;
import java.nio.file.Path;
import java.text.MessageFormat;
import java.time.Instant;
import java.util.Arrays;

import org.apache.maven.plugin.AbstractMojo;
import org.apache.maven.project.MavenProject;



// TODO
// replace javadoc with java annotations
// https://maven.apache.org/plugin-tools/maven-plugin-tools-java/index.html

/**
 * @goal generate-sources
 * @phase generate-sources
 */
public class VfsResourceManifestMojo extends AbstractMojo {
	
	/**
	 * @parameter property="project"
	 * @required
	 * @readonly
	 * @since 1.0
	 */
	MavenProject project;

	/**
	 * @parameter
	 * @required
	 */
	String sourceDirectory;

	/**
	 * @parameter default-value="resources.manifest"
	 */
	String manifestName;

	/**
	 * @parameter
	 */
	boolean length=false;

	/**
	 * @parameter
	 */
	String date;

	@Override
	public void execute() {
		try {
			File baseDir = project.getFile().getParentFile(); // Parent of pom.xml
			
			File vfsDir = new File(baseDir,sourceDirectory);
			if(!vfsDir.exists() || !vfsDir.isDirectory()) {
				getLog().error(MessageFormat.format("Invalid VFS directory {0}", vfsDir));
				return;
			}

			String fixedDateString = "2020-01-01T00:00:00Z";
			if(date!=null && date.length()>0) {
				if(date.equals("now")) {
					fixedDateString = Instant.now().toString();
				} else if(date.equals("file")) {
					fixedDateString = "file";
				} else if(date.equals("none")) {
					fixedDateString = null;
				} else {
					fixedDateString = date; 
				}
			}
			
			StringBuilder sb = new StringBuilder(2048);
			sb.append("# Generated by Maven plugin\n");
			addFiles( sb, vfsDir.toPath(), vfsDir, fixedDateString);
			String newContent = normalizeLineBreaks(sb.toString());
			
			File manifest = new File(vfsDir,manifestName);
			
			String oldContent = loadString(manifest);
			if(oldContent!=null) {
				oldContent = normalizeLineBreaks(oldContent);
				if(oldContent.equals(newContent)) {
					// Ok, do not override it...
					return;
				}
			}
			writeString(manifest, newContent);
		} catch (Exception e) {
			getLog().error("Unexpected VFS manifest generation error", e);
		}
	}
	
	public static String normalizeLineBreaks(String s) {
		if(s!=null && s.indexOf('\r')>=0) {
			// Normalize the lines breaks to make it compatible between the different platforms (Mac, Windows, ....)
			s = s.replace("\n\r", "\n");
			s = s.replace("\r\n", "\n");
			s = s.replace("\r", "\n");
		}
		return s;
	}
	
	private void addFiles(StringBuilder sb, Path basePath, File dir, String fixedDateString) {
		File[] files = dir.listFiles();
		Arrays.sort(files, (f1,f2) -> {
			boolean l1 = f1.isDirectory();
			boolean l2 = f2.isDirectory();
			if(l1!=l2) {
				return l1 ? 1 : -1;
			}
			return f1.getName().compareToIgnoreCase(f2.getName());
		});
		for(int i=0; i<files.length; i++) {
			File f = files[i];
			if(f.isFile() && accept(f)) {
				String path  = basePath.relativize(f.toPath()).toString();
				if(File.separatorChar!='/') {
					path = path.replace(File.separatorChar, '/');
				}
				if(!manifestName.equals(path)) {
					long lastModified = f.lastModified();
					sb.append(path);
					sb.append('\t');
					if(length) {
						sb.append(f.length());
					} else {
						sb.append(-1);
					}
					if(fixedDateString!=null) {
						sb.append('\t');
						if(fixedDateString.equals("file")) {
							String dateAsString = Instant.ofEpochMilli(lastModified).toString();
							sb.append(dateAsString);
						} else {
							sb.append(fixedDateString);
						}
					}
					sb.append('\n');
				}
			} else if(f.isDirectory()) {
				addFiles(sb,basePath,f,fixedDateString);
			}
		}
	}
	
	private boolean accept(File f) {
		String name = f.getName();
		if(name.equals(".DS_Store")) {
			return false;
		}
		if(name.equals(".gitignore")) {
			return false;
		}
		if(name.equals(".gitattributes")) {
			return false;
		}
		return true;
	}

	private String loadString(File f){
		if(f.exists() && f.isFile()) {
			StringBuilder sb = new StringBuilder(2048);
			try (FileReader r = new FileReader(f)) {
				char[] buf = new char[2048];
				int c;
				while( (c=r.read(buf))>=0 ) {
					sb.append(buf, 0, c);
				}
				return sb.toString();
			} catch(IOException ex) {
				getLog().info(MessageFormat.format("Error reading manifest file {0}", f), ex);
			}
		}
		return null;
	}

	private void writeString(File f, String s){
		try (Writer w = new OutputStreamWriter(new FileOutputStream(f), StandardCharsets.UTF_8)) {
			w.write(s);
		} catch(IOException ex) {
			getLog().error(MessageFormat.format("Error writing manifest file {0}", f), ex);
		}
	}
}
