/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

// https://docusaurus.io/docs/sidebar

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;

// module.exports = {
//   mySidebar: [
//     {
//       type: 'category',
//       label: 'Json Script',
//       items: [
//         {
//           type: 'doc',
//           id: 'json-script/getting-started',
//         },
//       ],
//     },
//     // {
//     //   type: 'category',
//     //   label: 'Java JSON',
//     // },
//     // {
//     //   type: 'link',
//     //   label: 'Github',
//     //   href: 'https://github.com/monflabs/Galta-Java',
//     // },
//   ],
// };
