<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.monflabs.galta</groupId>
		<artifactId>parent-utilities</artifactId>
		<version>${revision}</version>
	</parent>
	<artifactId>javacompiler</artifactId>
	<name>Galta Java Compiler</name>
	<description>Runtime compilation of Java source code to in-memory or file-system class files, with a class loader for the result.</description>

	<dependencies>
		<dependency>
			<groupId>org.monflabs.galta</groupId>
			<artifactId>utilities</artifactId>
    		<version>${revision}</version>
		</dependency>
		
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.monflabs.galta</groupId>
			<artifactId>test</artifactId>
    		<version>${revision}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.monflabs.galta</groupId>
			<artifactId>filesystem</artifactId>
    		<version>${revision}</version>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<configuration>
					<includes>
						<include>**/AllJavaCompilerTests.class</include>
					</includes>
				</configuration>
			</plugin>
		</plugins>
	</build>

</project>