/*
 * Copyright (c) 2019-2026 Philippe Riand
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.monflabs.galtajs.rt.builtins.standard.function;

import org.monflabs.galtajs.rt.JSRuntimeContext;
import org.monflabs.galtajs.rt.interpreter.InterpretedRuntimeContext;

/**
 * Parent context used to evaluate the source generated by the
 * {@code Function}/{@code GeneratorFunction}/{@code AsyncFunction}/
 * {@code AsyncGeneratorFunction} constructors. The resulting function is
 * never lexically nested in the calling scope - its strictness must come
 * solely from its own body's directive prologue (already correctly captured
 * at parse time by {@code ASTFunction.isForceStrictMode()}), never inherited
 * from the calling context. {@link #isStrictMode()} is hard-wired to
 * {@code false} so the runtime's usual "inherit strictness from the lexical
 * parent" composition (see {@code InterpretedFunctionRuntimeContext}) has
 * nothing to inherit; everything else (global access, variable resolution,
 * {@code this}) still delegates to the real calling context, since the
 * generated function still runs against the caller's realm. {@code getThis()}
 * is deliberately NOT overridden - it falls through to the real parent's
 * {@code this} lazily (the default {@code AbstractRuntimeContext} behavior),
 * rather than eagerly capturing {@code JSRuntimeContext.get().getThis()} at
 * construction time: the caller may be a derived class constructor's
 * {@code super()} call (e.g. {@code class Fn extends Function {}}), where
 * {@code this} is still TDZ-poisoned and reading it throws. The generated
 * function is never an arrow function, so this context's {@code getThis()}
 * is never actually consulted at runtime (only an arrow function's call()
 * path reads its parent context's {@code this}).
 */
public class FunctionConstructorParentContext extends InterpretedRuntimeContext {

	public FunctionConstructorParentContext(JSRuntimeContext parent) {
		super(parent);
	}

	@Override
	public boolean isStrictMode() {
		return false;
	}

	@Override
	public InterpretedRuntimeContext getVarDeclContext() {
		return this;
	}
}
