<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.monflabs.galta</groupId>
		<artifactId>parent-js</artifactId>
		<version>${revision}</version>
	</parent>
	<artifactId>js-transpiler-maven</artifactId>
	<description>Maven plugin that transpiles JavaScript sources to Java with GaltaJS at build time.</description>

	<packaging>maven-plugin</packaging>

	<name>GaltaJS Transpiler Maven Plugin</name>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<source>${maven.compiler.source}</source>
					<target>${maven.compiler.target}</target>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-plugin-plugin</artifactId>
				<configuration>
					<goalPrefix>monflabs</goalPrefix>
				</configuration>
			</plugin>
		</plugins>
	</build>

	<dependencies>
		<dependency>
			<groupId>org.monflabs.galta</groupId>
			<artifactId>js</artifactId>
			<version>${revision}</version>
		</dependency>

		<dependency>
			<groupId>org.apache.maven</groupId>
			<artifactId>maven-plugin-api</artifactId>
		</dependency>
		<dependency>
			<groupId>org.apache.maven</groupId>
			<artifactId>maven-core</artifactId>
		</dependency>
		<dependency>
		    <groupId>org.apache.maven.plugin-tools</groupId>
		    <artifactId>maven-plugin-annotations</artifactId>
		</dependency>

	</dependencies>
</project>